plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/CaseIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/TrailingWhitespace:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
  Max: 100

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/PredicateMethod:
  Enabled: true
  AllowedMethods:
    - type_cast

Naming/PredicatePrefix:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*_spec.rb

RSpec/DescribedClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Max: 25
  Exclude:
    - spec/workers/**/*_spec.rb

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleDescribes:
  Exclude:
    - spec/dbf/file_formats_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
